# Generated by Django 4.2.1 on 2023-06-30 21:22

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.CharField(max_length=45, primary_key=True, serialize=False, verbose_name='Código Curso')),
                ('anio_curso', models.CharField(max_length=4, verbose_name='Año')),
                ('matriculas_disponibles', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_calle', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('id_comuna', models.ForeignKey(db_column='id_comuna', on_delete=django.db.models.deletion.PROTECT, to='core.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoAlumno',
            fields=[
                ('id_estado_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado_alumno', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoMatricula',
            fields=[
                ('id_estado_matricula', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado_matricula', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoMensualidad',
            fields=[
                ('id_estado_mensualidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado_mensualidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoUsuario',
            fields=[
                ('id_estado_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado_usuario', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_genero', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GradoAcademico',
            fields=[
                ('id_grado_academico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_grado_academico', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id_jornada', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_jornada', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ListaAsignatura',
            fields=[
                ('id_lista_asignatura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_lista_asignatura', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ListaCurso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id_matricula', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('id_curso_matricula', models.ForeignKey(db_column='id_curso_matricula', on_delete=django.db.models.deletion.PROTECT, related_name='set_curso_matricula', to='core.curso')),
                ('id_estado_matricula', models.ForeignKey(db_column='id_estado_matricula', on_delete=django.db.models.deletion.PROTECT, to='core.estadomatricula')),
                ('id_ultimo_curso_aprobado', models.ForeignKey(db_column='id_ultimo_curso_aprobado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='set_ultimo_curso_aprobado', to='core.listacurso')),
            ],
        ),
        migrations.CreateModel(
            name='Mencion',
            fields=[
                ('id_mencion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_mencion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id_nacionalidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_nacionalidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NivelAcademico',
            fields=[
                ('id_nivel_academico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_nivel_academico', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id_parentesco', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_parentesco', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('run', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('p_nombre', models.CharField(max_length=255)),
                ('s_nombre', models.CharField(blank=True, max_length=255)),
                ('appaterno', models.CharField(max_length=255)),
                ('apmaterno', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono_fijo', models.BigIntegerField()),
                ('celular', models.BigIntegerField()),
                ('email', models.CharField(max_length=255, null=True)),
                ('id_direccion', models.ForeignKey(db_column='id_direccion', on_delete=django.db.models.deletion.PROTECT, to='core.direccion')),
                ('id_genero', models.ForeignKey(db_column='id_genero', on_delete=django.db.models.deletion.PROTECT, to='core.genero')),
                ('id_nacionalidad', models.ForeignKey(db_column='id_nacionalidad', on_delete=django.db.models.deletion.PROTECT, to='core.nacionalidad')),
            ],
        ),
        migrations.CreateModel(
            name='PrioridadNoticia',
            fields=[
                ('id_prioridad_noticia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_prioridad_noticia', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAnotacion',
            fields=[
                ('id_tipo_anotacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_anotacion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoApoderado',
            fields=[
                ('id_tipo_apoderado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_apoderado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAsistencia',
            fields=[
                ('id_tipo_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_asistencia', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCurso',
            fields=[
                ('id_tipo_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_curso', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMensualidad',
            fields=[
                ('id_tipo_mensualidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_mesualidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoNoticia',
            fields=[
                ('id_tipo_noticia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_noticia', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_usuario', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id_titulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_titulo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('run', models.OneToOneField(db_column='run', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='core.persona')),
                ('estudiante_prioritario', models.BooleanField(default=False)),
                ('enfermedad_cronica', models.CharField(max_length=255, null=True)),
                ('seguro_escolar_particular', models.CharField(max_length=255, null=True)),
                ('discapacidad_fisica', models.CharField(max_length=255, null=True)),
                ('evaluacion_profesional', models.BooleanField(default=False)),
                ('colegio_procedencia', models.CharField(max_length=255, null=True)),
                ('razon_cambio_colegio', models.CharField(max_length=255, null=True)),
                ('medio', models.CharField(max_length=255, null=True)),
                ('pie', models.BooleanField(default=False)),
                ('id_estado_alumno', models.ForeignKey(db_column='id_estado_alumno', on_delete=django.db.models.deletion.PROTECT, to='core.estadoalumno')),
                ('rut_madre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rut_madre_set', to='core.persona')),
                ('rut_padre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rut_padre_set', to='core.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('run', models.OneToOneField(db_column='run', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='core.persona')),
                ('vive_con_alumno', models.BooleanField()),
                ('id_nivel_academico', models.ForeignKey(db_column='id_nivel_academico', on_delete=django.db.models.deletion.PROTECT, to='core.nivelacademico')),
                ('id_parentesco', models.ForeignKey(db_column='id_parentesco', on_delete=django.db.models.deletion.PROTECT, to='core.parentesco')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id_noticia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('subtitulo', models.CharField(max_length=255)),
                ('cuerpo', models.TextField()),
                ('fecha_noticia', models.DateField()),
                ('imagen', models.ImageField(upload_to='media/noticias/')),
                ('id_prioridad_noticia', models.ForeignKey(db_column='id_prioridad_noticia', on_delete=django.db.models.deletion.PROTECT, to='core.prioridadnoticia')),
                ('id_tipo_noticia', models.ForeignKey(db_column='id_tipo_noticia', on_delete=django.db.models.deletion.PROTECT, to='core.tiponoticia')),
            ],
        ),
        migrations.CreateModel(
            name='Mensualidades',
            fields=[
                ('id_mensualidad', models.AutoField(primary_key=True, serialize=False)),
                ('monto_mensualidad', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('id_estado_mensualidad', models.ForeignKey(db_column='id_estado_mensualidad', on_delete=django.db.models.deletion.PROTECT, to='core.estadomensualidad')),
                ('id_matricula', models.ForeignKey(db_column='id_matricula', on_delete=django.db.models.deletion.PROTECT, to='core.matricula')),
                ('id_tipo_mensualidad', models.ForeignKey(db_column='id_tipo_mensualidad', on_delete=django.db.models.deletion.PROTECT, to='core.tipomensualidad')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='id_jornada',
            field=models.ForeignKey(db_column='id_jornada', on_delete=django.db.models.deletion.PROTECT, to='core.jornada', verbose_name='Tipo Jornada'),
        ),
        migrations.AddField(
            model_name='curso',
            name='id_lista_curso',
            field=models.ForeignKey(db_column='id_lista_curso', on_delete=django.db.models.deletion.PROTECT, to='core.listacurso', verbose_name='Lista de Cursos'),
        ),
        migrations.AddField(
            model_name='curso',
            name='id_tipo_curso',
            field=models.ForeignKey(db_column='id_tipo_curso', on_delete=django.db.models.deletion.PROTECT, to='core.tipocurso', verbose_name='Tipo Curso'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='id_region',
            field=models.ForeignKey(db_column='id_region', on_delete=django.db.models.deletion.PROTECT, to='core.region'),
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asignatura', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.PROTECT, to='core.curso')),
                ('id_lista_asignatura', models.ForeignKey(db_column='id_lista_asignatura', on_delete=django.db.models.deletion.PROTECT, to='core.listaasignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id_usuario', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('id_estado_usuario', models.ForeignKey(db_column='id_estado_usuario', on_delete=django.db.models.deletion.PROTECT, to='core.estadousuario')),
                ('id_tipo_usuario', models.ForeignKey(db_column='id_tipo_usuario', on_delete=django.db.models.deletion.PROTECT, to='core.tipousuario')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ResponsableAlumno',
            fields=[
                ('id_responsable_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('id_tipo_apoderado', models.ForeignKey(db_column='id_tipo_apoderado', on_delete=django.db.models.deletion.PROTECT, to='core.tipoapoderado')),
                ('run_alumno', models.ForeignKey(db_column='run_alumno', on_delete=django.db.models.deletion.PROTECT, related_name='set_run_alumno', to='core.alumno')),
                ('run_responsable', models.ForeignKey(db_column='run_responsable', on_delete=django.db.models.deletion.PROTECT, related_name='set_run_responsable', to='core.responsable')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('run', models.OneToOneField(db_column='run', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='core.persona')),
                ('magister', models.CharField(max_length=50, null=True)),
                ('doctorado', models.CharField(max_length=50, null=True)),
                ('id_grado_academico', models.ForeignKey(db_column='id_grado_academico', on_delete=django.db.models.deletion.PROTECT, to='core.gradoacademico')),
                ('id_mencion', models.ForeignKey(db_column='id_mencion', on_delete=django.db.models.deletion.PROTECT, to='core.mencion')),
                ('id_titulo', models.ForeignKey(db_column='id_titulo', on_delete=django.db.models.deletion.PROTECT, to='core.titulo')),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id_nota', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.FloatField()),
                ('id_asignatura', models.ForeignKey(db_column='id_asignatura', on_delete=django.db.models.deletion.PROTECT, to='core.asignatura')),
                ('run_alumno', models.ForeignKey(db_column='run_alumno', on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='core.alumno')),
            ],
        ),
        migrations.AddField(
            model_name='matricula',
            name='run_alumno',
            field=models.ForeignKey(db_column='run_alumno', on_delete=django.db.models.deletion.PROTECT, to='core.alumno'),
        ),
        migrations.CreateModel(
            name='GrupoFamiliar',
            fields=[
                ('id_grupo_familiar', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_familiar', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('id_parentesco', models.ForeignKey(db_column='id_parentesco', on_delete=django.db.models.deletion.PROTECT, to='core.parentesco')),
                ('run_alumno', models.ForeignKey(db_column='run_alumno', on_delete=django.db.models.deletion.PROTECT, to='core.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='CursoRepetido',
            fields=[
                ('id_curso_repetido', models.AutoField(primary_key=True, serialize=False)),
                ('anno_repitencia', models.IntegerField()),
                ('id_lista_curso', models.ForeignKey(db_column='id_lista_curso', on_delete=django.db.models.deletion.PROTECT, to='core.curso')),
                ('run_alumno', models.ForeignKey(db_column='run_alumno', on_delete=django.db.models.deletion.PROTECT, to='core.alumno')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor_jefe',
            field=models.ForeignKey(db_column='run_profesor_jefe', on_delete=django.db.models.deletion.PROTECT, to='core.profesor'),
        ),
        migrations.CreateModel(
            name='AsistenciaCurso',
            fields=[
                ('id_asistencia_curso', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fecha_asistencia', models.DateField()),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.PROTECT, to='core.curso')),
                ('id_tipo_asistencia', models.ForeignKey(db_column='id_tipo_asistencia', on_delete=django.db.models.deletion.PROTECT, to='core.tipoasistencia')),
                ('run_alumno', models.ForeignKey(db_column='run_alumno', on_delete=django.db.models.deletion.PROTECT, to='core.alumno')),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='run_profesor',
            field=models.ForeignKey(db_column='run_profesor', on_delete=django.db.models.deletion.PROTECT, to='core.profesor'),
        ),
        migrations.CreateModel(
            name='Anotacion',
            fields=[
                ('id_anotacion', models.AutoField(primary_key=True, serialize=False)),
                ('anotacion', models.CharField(max_length=200)),
                ('fecha_anotacion', models.DateField()),
                ('id_asignatura', models.ForeignKey(db_column='id_asignatura', on_delete=django.db.models.deletion.PROTECT, to='core.asignatura')),
                ('id_tipo_anotacion', models.ForeignKey(db_column='id_tipo_anotacion', on_delete=django.db.models.deletion.PROTECT, to='core.tipoanotacion')),
                ('run_alumno', models.ForeignKey(db_column='run_alumno', on_delete=django.db.models.deletion.PROTECT, to='core.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('run', models.OneToOneField(db_column='run', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='core.persona')),
                ('magister', models.CharField(max_length=50, null=True)),
                ('doctorado', models.CharField(max_length=50, null=True)),
                ('id_cargo', models.ForeignKey(db_column='id_cargo', on_delete=django.db.models.deletion.PROTECT, to='core.cargo')),
                ('id_grado_academico', models.ForeignKey(db_column='id_grado_academico', on_delete=django.db.models.deletion.PROTECT, to='core.gradoacademico')),
                ('id_mencion', models.ForeignKey(db_column='id_mencion', on_delete=django.db.models.deletion.PROTECT, to='core.mencion')),
                ('id_titulo', models.ForeignKey(db_column='id_titulo', on_delete=django.db.models.deletion.PROTECT, to='core.titulo')),
            ],
        ),
    ]
