# Generated by Django 3.x on YYYY-MM-DD HH:MM

from django.db import migrations, models

def create_message_models(apps, schema_editor):
    # Obtén el modelo
    Message = apps.get_model('core', 'Mensaje')
    EstadoMensaje = apps.get_model('core', 'EstadoMensaje')
    HistoriaMensaje = apps.get_model('core', 'HistoriaMensaje')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),  # Ajusta según el nombre correcto
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id_mensaje', models.AutoField(primary_key=True, serialize=False)),
                ('remitente', models.ForeignKey(on_delete=models.CASCADE, related_name='mensajes_enviados', to='core.usuario')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('asunto', models.CharField(max_length=255)),
                ('cuerpo', models.TextField()),
                ('permitir_respuestas', models.BooleanField(default=True)),
                ('enviar_por_mail', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoMensaje',
            fields=[
                ('id_estado_mensaje', models.AutoField(primary_key=True, serialize=False)),
                ('estado_leido', models.BooleanField(default=False)),
                ('fecha_leido', models.DateTimeField(blank=True, null=True)),
                ('mensaje', models.ForeignKey(on_delete=models.CASCADE, related_name='estados', to='core.mensaje')),
                ('destinatario', models.ForeignKey(on_delete=models.CASCADE, related_name='mensajes_recibidos', to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaMensaje',
            fields=[
                ('id_historia_mensaje', models.AutoField(primary_key=True, serialize=False)),
                ('estado_mensaje_padre', models.ForeignKey(on_delete=models.CASCADE, related_name='principal', to='core.estadomensaje')),
                ('estado_mensaje_respuesta', models.ForeignKey(on_delete=models.CASCADE, related_name='respuesta', to='core.estadomensaje')),
            ],
        ),
    ]
