# Generated by Django 5.1 on 2024-10-08 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='tarea',
        ),
        migrations.RemoveField(
            model_name='archivoentrega',
            name='entrega',
        ),
    ]
