# Generated by Django 4.2.1 on 2023-07-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCurso',
            fields=[
                ('id_estado_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado_curso', models.CharField(max_length=50)),
            ],
        ),
    ]
