# Generated by Django 5.1 on 2024-10-08 02:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_usuario_estado_usuario_alter_persona_s_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='media/archivos_tareas/')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='media/archivos_entrega/')),
            ],
        ),
        migrations.CreateModel(
            name='EntregaTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True)),
                ('fecha_entrega', models.DateTimeField(default=django.utils.timezone.now)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.alumno')),
                ('archivos', models.ManyToManyField(blank=True, to='core.archivoentrega')),
            ],
        ),
        migrations.AddField(
            model_name='archivoentrega',
            name='entrega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entregatarea'),
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id_tarea', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_fin', models.DateField()),
                ('archivos', models.ManyToManyField(blank=True, db_column='archivos', related_name='archivos_tareas', to='core.archivo')),
                ('asignatura', models.ForeignKey(db_column='id_asignatura', on_delete=django.db.models.deletion.PROTECT, to='core.asignatura')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.curso')),
                ('funcionario', models.ForeignKey(db_column='profesor', on_delete=django.db.models.deletion.PROTECT, to='core.funcionario')),
            ],
        ),
        migrations.AddField(
            model_name='entregatarea',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tarea'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tarea'),
        ),
    ]
