# Generated by Django 4.2.1 on 2023-07-01 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_estadocurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='id_estado_curso',
            field=models.ForeignKey(db_column='id_estado_curso', default=1, on_delete=django.db.models.deletion.PROTECT, to='core.estadocurso'),
            preserve_default=False,
        ),
    ]
