# Generated by Django 5.1.2 on 2024-11-04 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_reunion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reunion',
            name='estado_reunion',
            field=models.ForeignKey(db_column='id_estado_reunion', default='1', on_delete=django.db.models.deletion.PROTECT, to='core.estadoreunion'),
        ),
    ]
