# Generated by Django 5.1.1 on 2024-10-27 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_archivo_tarea_remove_archivoentrega_entrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueHorario',
            fields=[
                ('id_bloque', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_bloque', models.CharField(max_length=40)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], max_length=10)),
                ('asignatura', models.ForeignKey(db_column='id_asignatura', on_delete=django.db.models.deletion.PROTECT, to='core.asignatura')),
                ('bloque_horario', models.ForeignKey(db_column='id_bloque', on_delete=django.db.models.deletion.PROTECT, to='core.bloquehorario')),
                ('curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.PROTECT, to='core.curso')),
                ('profesor', models.ForeignKey(db_column='id_funcionario', on_delete=django.db.models.deletion.PROTECT, to='core.funcionario')),
            ],
            options={
                'unique_together': {('profesor', 'dia_semana', 'bloque_horario')},
            },
        ),
    ]
