# Generated by Django 5.1.2 on 2024-11-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_reunion_estado_reunion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTarea',
            fields=[
                ('id_tipo_tarea', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_tarea', models.CharField(max_length=25)),
            ],
        ),
    ]
