# Generated by Django 5.1.1 on 2024-10-29 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bloquehorario_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id_dia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_dia', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='horario',
            name='dia_semana',
            field=models.ForeignKey(db_column='id_dia', on_delete=django.db.models.deletion.PROTECT, to='core.diasemana'),
        ),
    ]
