# Generated by Django 5.1 on 2024-10-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_archivo_archivoentrega_entregatarea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fecha_fin',
            field=models.DateTimeField(),
        ),
    ]
