# Generated by Django 5.1.1 on 2024-11-22 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contacto_fecha_envio'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaContacto',
            fields=[
                ('id_respuesta_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje_respuesta', models.TextField()),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('contacto', models.ForeignKey(db_column='id_contacto', on_delete=django.db.models.deletion.PROTECT, to='core.contacto')),
                ('remitente', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
