# Generated by Django 5.1.1 on 2024-11-12 01:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_diasemana_alter_horario_dia_semana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='bloque_horario',
            field=models.ForeignKey(db_column='id_bloque', on_delete=django.db.models.deletion.CASCADE, to='core.bloquehorario'),
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id_mensaje', models.AutoField(primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=100)),
                ('cuerpo', models.TextField()),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('destinatario', models.ManyToManyField(related_name='mensajes_destinatario', to=settings.AUTH_USER_MODEL)),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensaje_remitente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoMensaje',
            fields=[
                ('id_estado_mensaje', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_leido', models.DateTimeField(blank=True, null=True)),
                ('leido', models.BooleanField(default=False)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL)),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='core.mensaje')),
            ],
        ),
    ]
