# Generated by Django 5.1.2 on 2024-11-14 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tipotarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='tipo_tarea',
            field=models.ForeignKey(db_column='id_tipo_tarea', default=1, on_delete=django.db.models.deletion.PROTECT, to='core.tipotarea'),
            preserve_default=False,
        ),
    ]
